name: Bug Report
description: Report a bug in ZCP
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: When I run `zcp audit`, it crashes with...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run `zcp audit --signer aws-kms`
        2. Wait for...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: ZCP Version
      description: Output of `zcp --version`
      placeholder: "zcp 0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux (x86_64)
        - Linux (arm64)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Any relevant log output
      render: shell
