name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: I'm frustrated when...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like it to work?
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds you've tried?
      
  - type: dropdown
    id: signer
    attributes:
      label: Related Signer (if applicable)
      options:
        - AWS KMS
        - GCP Cloud HSM
        - Azure Key Vault
        - Fireblocks
        - HashiCorp Vault
        - Other
