use crate::AuditReport;
use colored::*;
use std::fs::File;
use std::io::Write;

pub fn generate_bill_of_health(
    report: &AuditReport,
    daily_volume: u64,
    jitter_us: u64,
    output_path: Option<String>,
) -> std::io::Result<()> {
    let mut buffer = String::new();

    // --- Header ---
    buffer.push_str("# 🏥 INFRASTRUCTURE BILL OF HEALTH\n\n");
    buffer.push_str(&format!("**Date:** {}\n", report.timestamp));
    buffer.push_str(&format!(
        "**Platform:** {} (OS: {})\n",
        report.platform.os,
        if report.platform.is_linux {
            "Linux"
        } else {
            "Mac/Other"
        }
    ));
    buffer.push_str("\n---\n\n");

    // --- Executive Summary ---
    buffer.push_str("## 1. Executive Summary\n\n");
    if report.summary.score >= 90 {
        buffer.push_str("✅ **STATUS: HEALTHY**\n\n");
        buffer.push_str("Your infrastructure is optimized for HFT workloads.\n");
    } else {
        buffer.push_str("⚠️ **STATUS: CRITICAL LEAKAGE DETECTED**\n\n");
        buffer.push_str("Your current infrastructure is bleeding alpha due to high jitter and kernel interrupts.\n");
    }

    // --- The Jitter Tax Calculation ---
    // Model: 1ms latency = 0.01 bps slippage in high vol (approx)
    // Jitter is the "noise" that prevents predictable execution.
    // Annual Loss = Daily Vol * (Jitter/1000ms) * VolatilityFactor * 365
    let volatility_factor = 0.5; // Conservative baseline
    let jitter_ms = jitter_us as f64 / 1000.0;
    let daily_loss = (daily_volume as f64) * (jitter_ms / 1000.0) * volatility_factor; // Very rough heuristic for "slippage due to uncertainty"
    let annual_loss = daily_loss * 365.0;

    buffer.push_str("\n## 2. The Jitter Tax Calculation\n\n");
    buffer.push_str("| Metric | Value |\n");
    buffer.push_str("| :--- | :--- |\n");
    buffer.push_str(&format!(
        "| **Daily Volume** | ${:0.2}M |\n",
        daily_volume as f64 / 1_000_000.0
    ));
    buffer.push_str(&format!("| **Measured Jitter** | {} µs |\n", jitter_us));
    buffer.push_str(&format!(
        "| **Est. Annual Loss** | **${:0.0}** |\n",
        annual_loss
    ));
    buffer.push_str("\n> *\"Latency is the price of entry. Jitter is the price of failure.\"*\n");

    // --- Technical Findings ---
    buffer.push_str("\n## 3. Technical Findings\n\n");
    for check in &report.checks {
        let icon = if check.passed { "✅" } else { "❌" };
        buffer.push_str(&format!(
            "- {} **{}**: {}\n",
            icon, check.name, check.details
        ));
    }

    // --- Prescription ---
    buffer.push_str("\n## 4. Prescription: Sentinel Prime\n\n");
    buffer.push_str("To eliminate this Jitter Tax, upgrade to a **Sovereign Pod**.\n\n");
    buffer.push_str("- **Zero Jitter:** Keys pinned to dedicated CPU cores.\n");
    buffer.push_str("- **Hardware Enforced:** No 'noisy neighbors'.\n");
    buffer.push_str("- **Cost:** $96,000/year (Fixed).\n\n");

    let savings = annual_loss - 96_000.0;
    if savings > 0.0 {
        buffer.push_str(&format!(
            "### 📉 ROI Projection: +${:0.0} / year\n",
            savings
        ));
        buffer.push_str("Switching is net profitable immediately.\n");
    }

    buffer.push_str("\n---\n\n");
    buffer.push_str("*Generated by ZeroCopy Audit CLI*");

    // Write to file or stdout
    if let Some(path) = output_path {
        let mut file = File::create(path)?;
        file.write_all(buffer.as_bytes())?;
        println!("{} Bill of Health saved to details", "✓".green());
    } else {
        println!("{}", buffer);
    }

    Ok(())
}
